### ISSUE TITLE
NaN during training

### ISSUE THREAD

**Issue by n-gao** [google-deepmind/ferminet#22]
Hi,

I fiddled around with the `jax` code a bit and noticed that for small systems where any spin has only one electron the network will throw `nan` after some time.
```
ferminet --config ferminet/configs/atom.py --config.system.atom H --config.batch_size 4096 --config.pretrain.iterations 0
```
```
I0215 05:54:52.148167 139716596184896 train.py:461] Step 00538: -0.4999 E_h, pmove=0.97
I0215 05:54:52.173480 139716596184896 train.py:461] Step 00539: -0.4999 E_h, pmove=0.97
I0215 05:54:52.199377 139716596184896 train.py:461] Step 00540: nan E_h, pmove=0.97
I0215 05:54:52.224862 139716596184896 train.py:461] Step 00541: nan E_h, pmove=0.00
I0215 05:54:52.250287 139716596184896 train.py:461] Step 00542: nan E_h, pmove=0.00
```

I traced the issue down and found that this happens at the log abs determinant of the Slater determinant (in this case a 1x1 matrix). There is a small probability for a sample to be chosen such that the (1x1) matrix is exactly 0. After that, the code just produces `nan`.

**Comment by dpfau** [comment]
That makes sense. We fixed this in the TensorFlow version of the code, but
found it so rare for larger systems in JAX that it wasn't worth
implementing a fix. You could circumvent this by use of a custom derivative
if you like.

**Comment by n-gao** [comment]
Thanks for the quick response!
I could work around this issue by modifying the `logsumdet` function.
The following should work as a drop-in replacement:
```python
def logsumdet(
        xs: Sequence[jnp.ndarray],
        w: Optional[jnp.ndarray] = None) -> jnp.ndarray:
    # Special case if there is only one electron in any channel
    # We can avoid the log(0) issue by not going into the log domain
    dets = [x.reshape(-1) for x in xs if x.shape[-1] == 1]
    dets = functools.reduce(
        lambda a, b: a*b, dets
    ) if len(dets) > 0 else 1

    slogdets = [slogdet(x) for x in xs if x.shape[-1] > 1]
    maxlogdet = 0
    if len(slogdets) > 0:
        sign_in, logdet = functools.reduce(
            lambda a, b: (a[0]*b[0], a[1]+b[1]), slogdets
        )

        maxlogdet = jnp.max(logdet)
        det = sign_in * dets * jnp.exp(logdet - maxlogdet)
    else:
        det = dets

    if w is None:
        result = jnp.sum(det)
    else:
        result = jnp.dot(det, w)

    sign_out = jnp.sign(result)
    log_out = jnp.log(jnp.abs(result)) + maxlogdet
    return sign_out, log_out
```
This avoids working in the log domain if it's not necessary.

**Comment by dpfau** [comment]
Great! Can you send that as a pull request?

**Comment by jsspencer** [comment]
I'm curious about your technical set up (jax, jaxlib, and CUDA versions). The hydrogen atom works fine for me (several thousand iterations), though I agree the jax version is not as careful around this as the TF version.

The energy looks essentially converged by this point so I'm surprised you're hitting a NaN. Given the wavefunction shouldn't(!) contain any nodes, it can only happen far from the nucleus, so an MCMC configuration must have wandered quite a way away.  (As an aside, the default step size is way too small for hydrogen -- you should increase it to at least 0.5).

**Comment by n-gao** [comment]
Sure, here are the details:
|Lib|Version|
|---|---|
|jax|0.2.10|
|jaxlib|0.1.62|
|CUDA|10.2|

While the mean of the energy looked good, it wasn't converged yet (high variance). I checked the position of the electron and it was in a radius of 3A around the nucleus which isn't very afaik.
The error also occurs at higher step sizes.

**Comment by n-gao** [comment]
This error also occurs for Lithium far from the optimum.
```
I0306 02:47:37.867998 139629635032896 train.py:461] Step 00093: -6.6119 E_h, pmove=0.76
I0306 02:47:38.068941 139629635032896 train.py:461] Step 00094: -6.6105 E_h, pmove=0.76
I0306 02:47:38.270185 139629635032896 train.py:461] Step 00095: -6.6636 E_h, pmove=0.76
I0306 02:47:38.471880 139629635032896 train.py:461] Step 00096: nan E_h, pmove=0.76
I0306 02:47:38.671543 139629635032896 train.py:461] Step 00097: nan E_h, pmove=0.00
I0306 02:47:38.870149 139629635032896 train.py:461] Step 00098: nan E_h, pmove=0.00
```
Though, only if one sets `full_det` to `False`. As far as I can tell #23 fixes this.

On a side note: Is there a particular reason why `full_det` defaults to `True`? Isn't a wavefunction only antisymmetric with respect to permutation of electrons of the same spin? Also, it does not align with the definition of FermiNet in the papers.

**Comment by dpfau** [comment]
`full_det=True` does not mean that spin is ignored, and does not make
things fully antisymmetric wrt permutation of electrons of different spin.
It just means that instead of there being N_alpha non-zero orbitals for
alpha electrons and N_beta non-zero orbitals for beta electrons, there are
now N=N_alpha+N_beta nonzero orbitals for both alpha and beta electrons
(but the orbitals can be different!). This generalizes the `full_det=False`
case. It seems like it helps on some systems, though the difference is not
enormous.
