### ISSUE TITLE
Logdet Bug Similar to e9f8c64

### ISSUE THREAD

**Issue by mrlazy1708** [google-deepmind/ferminet#74]
Noticed that in `psiformer.py`, line 448, the logdet calculation for NES is still wrong by multiplying ndets together:

```python
      return batch_logdet_matmul(*orbitals)
```

A similar issue was fixed for FermiNet in e9f8c64ee170125e625c70390b94019723f8671b.

**Comment by jsspencer** [comment]
Thanks for spotting this, it's now fixed
