### ISSUE TITLE
Forces

### ISSUE THREAD

**Issue by tbraeckevelt** [google-deepmind/ferminet#83]
Dear developpers

Is there a method implemented in ferminet to calculate the interatomic forces? For example, as explained in https://doi.org/10.1063/5.0112344.

Kind regards

Tom

**Comment by AllanChain** [comment]
I recommend you to use https://github.com/bytedance/netobs. Besides, some new force estimators are introduced in https://doi.org/10.1039/D4FD00071D.

(I'm the author of https://github.com/bytedance/netobs and if you have any problems, feel free to raise issues there.)

**Comment by jsspencer** [comment]
Sorry, we don't have forces implemented right now. Pull requests are always welcome.
