### ISSUE TITLE
TypeError: _dense() missing 2 required positional arguments: 'axes' and 'with_reshape'

### ISSUE THREAD

**Issue by annulen** [google-deepmind/ferminet#87]
I've installed `ferminet` on Linux with Python 3.11 today using the following commands:
```
python -m venv --system-site-packages ~/venv/ferminet
. ~/venv/ferminet/bin/activate
pip install -U "jax[cuda12_pip]" -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html
pip install -e .
```
But when I try to run example calculation as 
```
ferminet --config ferminet/configs/atom.py --config.system.atom Li --config.batch_size 256 --config.pretrain.iterations 100
```
I'm getting the following output:
```
<...>
I1129 13:46:55.584216 139750111250240 train.py:384] Starting QMC with 1 XLA devices per host across 1 hosts.
converged SCF energy = -7.43242052759577  <S^2> = 0.75000054  2S+1 = 2.0000005
I1129 13:46:56.988999 139750111250240 train.py:584] No checkpoint found. Training new model.
I1129 13:47:01.371712 139750111250240 pretrain.py:344] Pretrain iter 00000: 0.0532642 0.890625
<...pretrain iterations...>
I1129 13:47:01.964662 139750111250240 pretrain.py:344] Pretrain iter 00099: 0.000944124 0.945312
Traceback (most recent call last):
  File "/home/ktokarev/venv/ferminet/bin/ferminet", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/mnt/storage/src/git/ferminet/bin/ferminet", line 39, in <module>
    app.run(main)
  File "/usr/lib/python3.11/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/usr/lib/python3.11/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
             ^^^^^^^^^^
  File "/mnt/storage/src/git/ferminet/bin/ferminet", line 35, in main
    train.train(cfg)
  File "/mnt/storage/src/git/ferminet/ferminet/train.py", line 852, in train
    opt_state = optimizer.init(params, subkeys, data)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ktokarev/venv/ferminet/lib/python3.11/site-packages/kfac_jax/_src/optimizer.py", line 1025, in init
    return self._init(params, rng, batch, func_state)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ktokarev/venv/ferminet/lib/python3.11/site-packages/kfac_jax/_src/utils/staging.py", line 277, in decorated
    outs = func(instance, *args)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ktokarev/venv/ferminet/lib/python3.11/site-packages/kfac_jax/_src/optimizer.py", line 993, in _init
    estimator_state=self.estimator.init(
                    ^^^^^^^^^^^^^^^^^^^^
  File "/home/ktokarev/venv/ferminet/lib/python3.11/site-packages/kfac_jax/_src/utils/misc.py", line 342, in wrapped
    return method(instance, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ktokarev/venv/ferminet/lib/python3.11/site-packages/kfac_jax/_src/curvature_estimator/block_diagonal.py", line 390, in init
    self.finalize(func_args)
  File "/home/ktokarev/venv/ferminet/lib/python3.11/site-packages/kfac_jax/_src/utils/misc.py", line 315, in finalize
    self._finalize(*args, **kwargs)
  File "/home/ktokarev/venv/ferminet/lib/python3.11/site-packages/kfac_jax/_src/curvature_estimator/block_diagonal.py", line 375, in _finalize
    self._jaxpr = self._jaxpr_extractor(func_args)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ktokarev/venv/ferminet/lib/python3.11/site-packages/kfac_jax/_src/tracer.py", line 466, in get_processed_jaxpr
    closed_jaxpr, _ = retrieve(func_args)
                      ^^^^^^^^^^^^^^^^^^^
  File "/home/ktokarev/venv/ferminet/lib/python3.11/site-packages/kfac_jax/_src/tracer.py", line 432, in retrieve
    processed_jaxpr = ProcessedJaxpr.make_from_func(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ktokarev/venv/ferminet/lib/python3.11/site-packages/kfac_jax/_src/tracer.py", line 321, in make_from_func
    func = tgm.auto_register_tags(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ktokarev/venv/ferminet/lib/python3.11/site-packages/kfac_jax/_src/tag_graph_matcher.py", line 2080, in auto_register_tags
    func_graph, tagged_locations = _auto_register_tags(
                                   ^^^^^^^^^^^^^^^^^^^^
  File "/home/ktokarev/venv/ferminet/lib/python3.11/site-packages/kfac_jax/_src/tag_graph_matcher.py", line 1849, in _auto_register_tags
    sub_graph, sub_tag_locations = _auto_register_tags(
                                   ^^^^^^^^^^^^^^^^^^^^
  File "/home/ktokarev/venv/ferminet/lib/python3.11/site-packages/kfac_jax/_src/tag_graph_matcher.py", line 1915, in _auto_register_tags
    matches = find_layer_tags_and_patterns(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ktokarev/venv/ferminet/lib/python3.11/site-packages/kfac_jax/_src/tag_graph_matcher.py", line 864, in find_layer_tags_and_patterns
    match = match_pattern(
            ^^^^^^^^^^^^^^
  File "/home/ktokarev/venv/ferminet/lib/python3.11/site-packages/kfac_jax/_src/tag_graph_matcher.py", line 767, in match_pattern
    if len(pattern.jaxpr.outvars) != len(root_eqn.outvars):
           ^^^^^^^^^^^^^
  File "/home/ktokarev/venv/ferminet/lib/python3.11/site-packages/kfac_jax/_src/tag_graph_matcher.py", line 478, in jaxpr
    return self.graph.jaxpr
           ^^^^^^^^^^
  File "/usr/lib/python3.11/functools.py", line 1001, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/home/ktokarev/venv/ferminet/lib/python3.11/site-packages/kfac_jax/_src/tag_graph_matcher.py", line 488, in graph
    return make_jax_graph(
           ^^^^^^^^^^^^^^^
  File "/home/ktokarev/venv/ferminet/lib/python3.11/site-packages/kfac_jax/_src/tag_graph_matcher.py", line 355, in make_jax_graph
    closed_jaxpr, out_shapes = jax.make_jaxpr(func, return_shape=True)(*func_args)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: _dense() missing 2 required positional arguments: 'axes' and 'with_reshape'
--------------------
```

Same error reproduces for me with other calculations. I also tried switching used `kfac_jax` revision from the head of `main` branch to a few recent commits, with exactly the same error happening.

Any idea what's going on and how can I make it work?

**Comment by SeldonHarry** [comment]
This bug also popped up when I tried to run it on a server. It seems that problems are resulted from kfac optimizer. After I substitude it by adam, everything works fine. However, the same version of modified codes on my own server works perfect with kfac optimzer, which was deployed in September. I'm also trying to figure out what's wrong with the mess. It is puzzling for kfac lib hasn't be updated since April and I use version 0.0.6 consistently.

**Comment by annulen** [comment]
>It is puzzling for kfac lib hasn't be updated since April and I use version 0.0.6 consistently.

By default FermiNet uses master of `kfac-jax` which is updated quite often (and, according to its git history, those updates sometimes break things in other projects). I've tried to use 0.0.6 but it just didn't work.

**Comment by SeldonHarry** [comment]
It occurs to me that kfac-jax has a recent commit, which seems not to be compatible with this version of ferminet. So you can just pull down a history commit of version 0.0.6  kfac-jax and mannualy install it via `python -m build` command. I fixed this problem by replacing the latest version with commit hash code "315f59e".

**Comment by dibbla** [comment]
> It occurs to me that kfac-jax has a recent commit, which seems not to be compatible with this version of ferminet. So you can just pull down a history commit of version 0.0.6 kfac-jax and mannualy install it via `python -m build` command. I fixed this problem by replacing the latest version with commit hash code "315f59e".

Hi @SeldonHarry 

Thanks for the inspiring hint! I am also struggling with running the sample code, but with a different error. I am wondering if you have encountered this problem #88 
And I can't appreciate more if you can share the environment configuration that you are using. Many thanks in advance.

**Comment by annulen** [comment]
>I fixed this problem by replacing the latest version with commit hash code "315f59e".

I'm sorry but I can see no such commit in kfac-jax: google-deepmind/kfac-jax@315f59e

**Comment by jsspencer** [comment]
This is from a change in the KFAC API (specifically [this commit](https://github.com/google-deepmind/kfac-jax/commit/8272409a02ab90aedfaefe9436245bb4d0b9c8e4)). I've just push an update which handles this change. (An alternative, as @SeldonHarry suggests, is to ping kfac-jax to a version just before the API change.)

Please re-open if this doesn't fix things for you.

**Comment by SeldonHarry** [comment]
@dibbla I haven't met such error till now. But I guess that it's caused  by jax and jaxlib. My packgages managed by pip is listed as follows:
<details>
  <summary>config</summary>

Package                  Version     Editable project location
------------------------ ----------- ----------------------------------------
absl-py                  2.1.0
attrs                    24.2.0
build                    1.2.2.post1
cachetools               5.5.0
chex                     0.1.87
cloudpickle              3.1.0
decorator                5.1.1
distrax                  0.1.5
dm-tree                  0.1.8
etils                    1.11.0
ferminet                 0.2         /mnt/nas2/home/pankaisen/seldon/GraphQMC
flax                     0.10.2
folx                     0.2.12
fsspec                   2024.10.0
gast                     0.6.0
h5py                     3.12.1
humanize                 4.11.0
immutabledict            4.2.1
importlib_resources      6.4.5
iniconfig                2.0.0
jax                      0.4.34
jax-cuda12-pjrt          0.4.34
jax-cuda12-plugin        0.4.34
jaxlib                   0.4.34
jaxtyping                0.2.36
jraph                    0.0.6.dev0
kfac-jax                 0.0.6
markdown-it-py           3.0.0
mdurl                    0.1.2
ml_collections           1.0.0
ml_dtypes                0.5.0
msgpack                  1.1.0
nest-asyncio             1.6.0
numpy                    2.1.3
nvidia-cublas-cu12       12.6.4.1
nvidia-cuda-cupti-cu12   12.6.80
nvidia-cuda-nvcc-cu12    12.6.85
nvidia-cuda-runtime-cu12 12.6.77
nvidia-cudnn-cu12        9.6.0.74
nvidia-cufft-cu12        11.3.0.4
nvidia-cusolver-cu12     11.7.1.2
nvidia-cusparse-cu12     12.5.4.2
nvidia-ml-py             12.535.161
nvidia-nccl-cu12         2.23.4
nvidia-nvjitlink-cu12    12.6.85
nvitop                   1.3.2
opt_einsum               3.4.0
optax                    0.2.4
orbax-checkpoint         0.10.2
packaging                24.2
pandas                   2.2.3
parameterized            0.9.0
pip                      24.2
pluggy                   1.5.0
protobuf                 5.29.1
psutil                   6.1.0
pyblock                  0.6
Pygments                 2.18.0
pyproject_hooks          1.2.0
pyscf                    2.7.0
pytest                   8.3.4
python-dateutil          2.9.0.post0
pytz                     2024.2
PyYAML                   6.0.2
rich                     13.9.4
scipy                    1.14.1
setuptools               75.1.0
simplejson               3.19.3
six                      1.17.0
tensorflow-probability   0.25.0
tensorstore              0.1.69
termcolor                2.5.0
toolz                    1.0.0
typing_extensions        4.12.2
tzdata                   2024.2
wheel                    0.44.0
zipp                     3.21.0
</details>
