### ISSUE TITLE
Example code error, list index out of range with H2 example

### ISSUE THREAD

**Issue by dibbla** [google-deepmind/ferminet#88]
When trying to execute the sample code, encountered following error:
```bash
INFO:absl:Starting QMC with 1 XLA devices per host across 1 hosts.
converged SCF energy = -1.08928257473103  <S^2> = 4.3076653e-14  2S+1 = 1
INFO:absl:No checkpoint found. Training new model.
Traceback (most recent call last):
  File "/home/test/scientific_tools_validation/ferminet_scripts/installation_validate.py", line 24, in <module>
    train.train(cfg)
  File "/home/test/scientific_tools_validation/pkgs/ferminet/ferminet/train.py", line 680, in train
    params, data.positions = pretrain.pretrain_hartree_fock(
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/test/scientific_tools_validation/pkgs/ferminet/ferminet/pretrain.py", line 342, in pretrain_hartree_fock
    data, params, opt_state_pt, loss, pmove = pretrain_step(
                                              ^^^^^^^^^^^^^^
  File "/home/test/scientific_tools_validation/pkgs/ferminet/ferminet/pretrain.py", line 255, in pretrain_step
    data, pmove = mcmc_step(full_params, data, key, width=0.02)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/test/scientific_tools_validation/pkgs/ferminet/ferminet/mcmc.py", line 277, in mcmc_step
    new_data, key, _, num_accepts = lax.fori_loop(
                                    ^^^^^^^^^^^^^^
IndexError: list index out of range
--------------------
```

**Comment by dibbla** [comment]
update: I have tried multiple combinations with kfac-jax and ferminet, but none of these combination works. For example, updates on Sep 24 with kfac-jax on Sep 17. Any suggestion can help.

**Comment by jsspencer** [comment]
Optimization during pretraining does not use KFAC. I can't reproduce your error using then config:
```
from ferminet import base_config
from ferminet.utils import system                                                                                                                                                   ication=b/313092190^C

# Settings in a config files are loaded by executing the the get_config
# function.
def get_config():
  # Get default options.
  cfg = base_config.default()
  # Set up molecule
  cfg.system.electrons = (1,1)
  cfg.system.molecule = [system.Atom('H', (0, 0, -1)), system.Atom('H', (0, 0, 1))]

  # Set training hyperparameters
  cfg.batch_size = 256
  cfg.pretrain.iterations = 100
```

Can you share:

- config used
- command used to run ferminet
- versions of jax and pyscf
- 
please?

**Comment by dibbla** [comment]
> Optimization during pretraining does not use KFAC. I can't reproduce your error using then config:
> 
> ```
> from ferminet import base_config
> from ferminet.utils import system                                                                                                                                                   ication=b/313092190^C
> 
> # Settings in a config files are loaded by executing the the get_config
> # function.
> def get_config():
>   # Get default options.
>   cfg = base_config.default()
>   # Set up molecule
>   cfg.system.electrons = (1,1)
>   cfg.system.molecule = [system.Atom('H', (0, 0, -1)), system.Atom('H', (0, 0, 1))]
> 
>   # Set training hyperparameters
>   cfg.batch_size = 256
>   cfg.pretrain.iterations = 100
> ```
> 
> Can you share:
> 
> * config used
> * command used to run ferminet
> * versions of jax and pyscf
> 
> please?

Hi @jsspencer 

Thanks for the fast reply! Here is the process I used for setup:
```bash
conda create -n ferminet python=3.11
conda activate ferminet
conda install nvidia/label/cuda-12.0.1::cuda # actually not using CUDA right now
git clone git@github.com:google-deepmind/ferminet.git
cd ferminet/
pip install -e .
```

Here is how I execute the ferminet example code:
```bash
ferminet --config ferminet/configs/atom.py --config.system.atom Li --config.batch_size 256 --config.pretrain.iterations 100
```
This result in the same error as I reported above.

Here are some environment information:
- jax = 0.4.36
- jaxlib = 0.4.36
- kfac-jax = 0.0.6

Everything is update-to-date on Dec 8, Pacific Time. Any suggestion on fixing this?

**Comment by jsspencer** [comment]
This is because the latest chex release is not compatible with jax 0.4.36. A new release will hopefully be available soon. In the meantime, you can install the latest commit of chex using

```
pip install -U 'git+https://github.com/google-deepmind/chex@f0b6b503a5fb625a380a6b318ec1f6d2abd9b9bf'
```

**Comment by dibbla** [comment]
> Your 2. (installing dev version of chex) should be sufficient to use jax 0.4.36 and will enable you to use KFAC (default optimizer).

O Cool! Your version works, which is better!

Thanks for the help! Closing this issue as problem resolved.
